CREATE TABLE set (
	code VARCHAR(10) PRIMARY KEY,
	name VARCHAR(50),
	gathererCode VARCHAR(10),
	oldCode VARCHAR(10),
	magicCardsInfoCode VARCHAR(10),
	releaseDate DATE,
	border VARCHAR(10),
	type VARCHAR(15),
	block VARCHAR(20),
	onlineOnly BOOLEAN
);

CREATE TABLE card (
	multiverseid INT PRIMARY KEY,
	setCode VARCHAR(10),
	name VARCHAR(200),
	manaCost VARCHAR(100),
	decimal cmc,
	colors VARCHAR(100),
	colorIdentity VARCHAR(100),
	type VARCHAR(100),
	supertypes VARCHAR(100),
	types VARCHAR(100),
	subtypes VARCHAR(100),
	rarity VARCHAR(10),
	text VARCHAR(500),
	flavor VARCHAR(500),
	artist VARCHAR(100),
	number INT,
	power INT,
	toughness INT,
	loyalty INT,
	layout VARCHAR(25),
	mciNumber VARCHAR(25),
	imageName VARCHAR(100),
	watermark VARCHAR(25),
	timeshifted BOOLEAN,
	hand INT,
	life INT,
	reserved BOOLEAN,
	starter BOOLEAN,
	releaseDate VARCHAR(25),
	id VARCHAR(41),
	FOREIGN KEY (setCode),
		REFERENCES set(code),
		ON DELETE CASCADE
);
